# SpringBoot加载配置文件（加载到Spring Environment中）顺序：
# project/config -> project -> classpath:project/src/main/resources/config -> classpath:project/src/main/resources
# 默认配置文件名application.properties|yml, 指定配置文件名启动参数--spring.config.name|--spring.config.location=classpath:/
server:
  port: 80
  # 配置https connector（关闭http connector）
  ssl:
    key-store: localhttps.cert
    key-alias: tomcathttps
    key-store-password: qing3gan
# 类型安全配置
book1:
  name: 红楼梦
  author: 曹雪芹
  price: 20
  favorites:
    - 贾宝玉
    - 林黛玉
book2:
  books:
    - name: 三国演义
      author: 罗贯中
      price: 30
      favorites:
        - 刘备
        - 关羽
        - 张飞
    - name: 水浒传
      author: 施耐庵
      price: 40
      favorites:
        - 晁盖
        - 鲁智深
        - 李逵
spring:
  # profile优先级：配置文件 -> application
  profiles:
    active: dev
  # 响应编码配置
  http:
    encoding:
      force-response: true
  # 静态资源配置
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:static/
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:\\WorkspaceTemp
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  # 单数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql:///demo?useSSL=false
##    url: jdbc:mysql:///jpa?useSSL=false
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    database: mysql
#    hibernate:
#      # 项目启动时根据实体类更新数据库中对应的表
#      ddl-auto: update
#    properties:
#      hiernate:
#        # 数据库方言
#        dialect: org.hibernate.dialect.MySQL57Dialect
  # 多数据源
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///multi_source_1?useSSL=false
      username: root
      password: root
    two:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///multi_source_2?useSSL=false
      username: root
      password: root
  jpa:
    # 与单数据源配置有区别，配置均从JpaProperties.getProperties()中获取
    properties:
      show-sql: true
      database: mysql
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        hbm2ddl:
          auto: update
  redis:
    # 单数据源
#    database: 0
#    host: 192.168.37.130
#    port: 6379
#    password: root
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 8
    cluster:
      ports:
        - 8001
        - 8002
        - 8003
        - 8004
        - 8005
        - 8006
        - 8007
        - 8008
      host: 192.168.37.130
      poolConfig:
        max-total: 8
        max-idle: 8
        max-wait-timeout: -1
        min-idle: 8