spring:
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
    user: admin
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest